import turtle
turtle.getscreen()
turtle.pensize(5)
turtle.bgcolor("Yellow")
turtle.pencolor("Blue")
turtle.penup()

turtle.setposition(-200,-100)

turtle.pendown()
turtle.fillcolor("Red")
turtle.begin_fill()

turtle.forward(100)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(70)
turtle.right(90)
turtle.forward(140)
turtle.right(90)
turtle.forward(70)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(200)
turtle.end_fill()

turtle.penup()
turtle.setposition(0,-100)
turtle.pendown()
turtle.pencolor("Red")
turtle.fillcolor("Blue")
turtle.begin_fill()
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(120)
turtle.left(90)
turtle.forward(75)
turtle.right(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(75)
turtle.left(90)
turtle.forward(40)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(120)
turtle.left(90)
turtle.forward(75)
turtle.right(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(75)
turtle.left(90)
turtle.forward(40)

turtle.hideturtle()
turtle.end_fill()
turtle.done()

